### ISSUE TITLE
netmask wrong

### ISSUE THREAD

**Issue by tessus** [ba9f11ecc3497d9993b933fdc2bd61e5/ipcalc6#3]
```
$ ipcalc6 fddf:2233:4444::/8

Type:		Unique-Local Address
Address:	fddf:2233:4444:0000:0000:0000:0000:0000		NetMask:	8
Hosts/Net:	19342813113834066795298816

Address:	fddf:2233:4444:0000:0000:0000:0000:0000
Netmask:	ffff:ffff:ffff:0000:0000:0000:0000:0000
HostMin:	fddf:2233:4444:0000:0000:0000:0000:0000
HostMax:	fddf:2233:4444:ffff:ffff:ffff:ffff:ffff

Address:	1111110111011111.0010001000110011.0100010001000100.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000
NetMask:	1111111111111111.1111111111111111.1111111111111111.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000
HostMin:	1111110111011111.0010001000110011.0100010001000100.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000
HostMax:	1111110111011111.0010001000110011.0100010001000100.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111

$ ipcalc6 fddf:2233:4444::/48

Type:		Unique-Local Address
Address:	fddf:2233:4444:0000:0000:0000:0000:0000		NetMask:	48
Hosts/Net:	19342813113834066795298816

Address:	fddf:2233:4444:0000:0000:0000:0000:0000
Netmask:	ffff:ffff:ffff:0000:0000:0000:0000:0000
HostMin:	fddf:2233:4444:0000:0000:0000:0000:0000
HostMax:	fddf:2233:4444:ffff:ffff:ffff:ffff:ffff

Address:	1111110111011111.0010001000110011.0100010001000100.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000
NetMask:	1111111111111111.1111111111111111.1111111111111111.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000
HostMin:	1111110111011111.0010001000110011.0100010001000100.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000
HostMax:	1111110111011111.0010001000110011.0100010001000100.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111
```

In the first example the netmask should be:

```
ffff:0000:0000:0000:0000:0000:0000:0000
1111111111111111.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000
```

It seems that all netmasks between /7 and /64 have a problem.

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment]
I thought the same as you when I was tired at midnight, but we should not confuse the "most significant bits" with the netmask (and the 48-bit routing prefix that gets constructed with the 40 mandatory random bits.). The netmask will indeed be /48.

https://en.wikipedia.org/wiki/Unique_local_address 

I could also force the netmask to be higher than 48 or spit an error, what do you think?

**Comment by tessus** [comment]
Nope, for a local address the routing prefix has 48 bits, (prefix `fd` + global id), 8 bit subnet, and 64 bit interface (your hosts in that subnet).

But when I specify a netmask of /8, it still should be `ffff:0000:0000:0000:0000:0000:0000:0000` (but I will have to test global addresses and not local addresses). In reality a unique local address cannot have a /8 netmask, or anything lower than /64. However, the routing prefix has /48, so ths is why /48 and higher should be allowed for unique local addresses.

> I could also force the netmask to be equal or higher than 48 or spit an error, what do you think?

Yes, this makes sense for a unique local address.

So either a warning would be good

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment]
Ok, so throwing an error for  Unique local address with a prefix smaller than /48 seems the way to go.

The netmask terminology should be removed everywhere and replace with "prefix".

Prefix is definitely broken for Global Unicast with a prefix smaller than /48 (tested with google advertised block 2a00:1450:4000::/37) both in the binary and the hex representation. I will have to work on this.

the warning still seems to be relevant since only ISP's,  google and the like will advertise smaller prefix than /48  
WARNING : netmask /37 is smaller than /48, this is unusual if ip of type : Global Unicast Address

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment]
> I will have to work on this / the smallest prefix for allocations should be a /12.

This brings me to the scope of this tool and the intended usage I had in mind for it. I made this project mostly to learn a bit of rust and because I did not like the existing ipv6 calculator(ipv6calc) lack of visual binary reference.

I think it is fair to say that most people(except network admins @ Big corp & ISP's) will only deal with /48 when segmenting a ipv6 network with Global unicast addresses. They could look up addresses with a prefix smaller than /48 out of curiosity but I hardly see the value it would bring an average user that implement ipv6.

We should also have to keep in mind that the minimum routable end address will always have a minimum prefix of /48.

I forsee different problems if I add support the prefixes /12 to /48 namely, the Hosts/Net will require exponent notation instead of decimal­.

An option is saying that prefix /12 to /48 is valid but that this tool only support /48+ prefixes (the most common).

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment]
This will be the new behavior, I updated the README accordingly, let me know if you think the error message could be better formulated.

ipcalc6 2a00:1450:4000::/37

ERROR : prefix /37 is smaller than /48, this is used in CIDR routing but not allowed as a prefix for an ip address

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment]
I think this is the correct resolution if we look at it from an address perspective. Yes you will find /32 in the routing tables of the backbone internet routers, but when you assign an address to a device, the prefix will never be smaller than /48

**Comment by tessus** [comment]
I think that makes sense. Thanks for the explanation. I would only change a small part of the error message:

```
ERROR: prefix /37 is smaller than /48, this can used as a routing prefix, but is not allowed as a prefix for an IP address
```

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment]
error message updated.

**Comment by tessus** [comment]
Awesome. Thanks.
